---
- hosts: digitalocean
  user: freebsd
  sudo: yes
  vars:
    hostname: codeways.org
  tasks:
    - name: install mail server
      pkgng: name=opensmtpd state=present
    - name: install imap server
      pkgng: name=dovecot2 state=present
    - name: update configuration
      template: src=smtpd.conf.j2 dest=/usr/local/etc/mail/smtpd.conf
    - name: Start OpenSMTPD
      service: name=smtpd state=started

