---
- hosts: digitalocean
  user: freebsd
  sudo: yes
  vars:
    device: vtnet0
    mail_fqdn: mail.codeways.org
    req_dn: NL
    state: NL
    locality: Amsterdam
    organization: codeways
    organizational_unit: codeways
    common_name: mail.codeways.org
    email_contact: postmaster@codeways.org
  tasks:
    - name: install mail server
      pkgng: name=opensmtpd state=present
    - name: install imap server
      pkgng: name=dovecot2 state=present
    - name: Creates ssl certs directory
      file: path=/etc/ssl/certs state=directory
    - name: Creates ssl private directory
      file: path=/etc/ssl/private state=directory
    - name: update dovecot ssl configuration
      template: src=dovecot-openssl.cnf.j2 dest=/usr/local/share/examples/dovecot/dovecot-openssl.cnf
    - name: generate ssl certificate for imap server
      command: /bin/sh /usr/local/share/examples/dovecot/mkcert.sh
      args:
        chdir: /usr/local/share/examples/dovecot
        creates: /etc/ssl/certs/dovecot.pem
    - name: generate ssl certificate for mail server
      command: openssl req -new -nodes -x509 -subj "/C={{req_dn}}/ST={{state}}/L={{locality}}/O={{organization}}/CN={{mail_fqdn}}" -days 3650 -keyout /etc/ssl/private/{{mail_fqdn}}.key -out /etc/ssl/certs/{{mail_fqdn}}.crt -extensions v3_ca creates=/etc/ssl/certs/{{mail_fqdn}}.crt
    - name: permissions for certificates
      file: path=/etc/ssl/private/{{mail_fqdn}}.key owner=root group=wheel mode=700
    - name: update configuration
      template: src=smtpd.conf.j2 dest=/usr/local/etc/mail/smtpd.conf
    - name: install dovecot config templates
      shell: cp -r example-config/* .
      args:
        chdir: /usr/local/etc/dovecot
        creates: /usr/local/etc/dovecot/dovecot.conf
    - name: install docvecot configuration
      template: src=dovecot.conf.j2 dest=/usr/local/etc/dovecot/local.conf
    - name: disable sendmail service
      command: /usr/sbin/sysrc sendmail_enable=NO
    - name: disable sendmail submit
      command: /usr/sbin/sysrc sendmail_submit_enable=NO
    - name: disable sendmail outbound
      command: /usr/sbin/sysrc sendmail_outbound_enable=NO
    - name: disable sendmail queue
      command: /usr/sbin/sysrc sendmail_msp_queue_enable=NO
    - name: enable opensmtpd server
      command: /usr/sbin/sysrc smtpd_enable=YES
    - name: enable imap server
      command: /usr/sbin/sysrc dovecot_enable=YES
    - name: Start OpenSMTPD
      service: name=smtpd state=started
    - name: Start dovecot
      service: name=dovecot state=started