---
- name: add standard user
  user: name={{username}} password={{password}} shell=/usr/local/bin/zsh groups=wheel append=yes generate_ssh_key=yes ssh_key_bits=2048 ssh_key_file=.ssh/id_rsa
- name: configure zsh for standard user
  copy: src=zshrc dest=/home/{{username}}/.zshrc owner={{username}} group={{username}} mode=644