---
- name: set hostname
  command: hostname {{fqdn}}
- name: persist hostname
  template: src=hostname.j2 dest=/etc/hostname owner=root group=wheel mode=0644
- name: enable firewall
  command: /usr/sbin/sysrc pf_enable=YES
  tags: firewall
- name: configuring firewall
  command: /usr/sbin/sysrc pflog_enable=YES
  tags: firewall
  notify:
    - restart firewall
- name: configuring firewall
  template: src=pf.conf.j2 dest=/etc/pf.conf owner=root group=wheel mode=0644
  tags: firewall
  notify:
    - restart firewall
- name: set timezone
  command: /usr/sbin/tzsetup -s {{timezone}}
  tags: ntp
  notify:
    - restart ntpd
- name: enable ntp
  command: /usr/sbin/sysrc ntpd_enable=YES
  tags: ntp
- name: ntp sync on start
  command: /usr/sbin/sysrc ntpd_sync_on_start=YES
  tags: ntp
- name: install sshguard
  pkgng: name=sshguard-pf state=present
  tags: firewall
- name: enable sshguard
  command: /usr/sbin/sysrc sshguard_enable=YES
  notify:
    - restart sshguard
  tags: firewall
- name: configure sshguard
  command: /usr/sbin/sysrc sshguard_safety_thresh="30"
  notify:
    - restart sshguard
  tags: firewall
- name: configure sshguard
  command: /usr/sbin/sysrc sshguard_pardon_min_interval="600"
  notify:
    - restart sshguard
  tags: firewall
- name: configure sshguard
  command: /usr/sbin/sysrc sshguard_prescribe_interval="7200"
  notify:
    - restart sshguard
  tags: firewall
